name: Deploy

on:
  push:
    branches: [main, beta, alpha]

concurrency:
  group: publish-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
  
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: |
          echo "=== Start PNPM INSTALL ==="
          pnpm install --loglevel=warn
          echo "=== End PNPM INSTALL ==="
        continue-on-error: false

      - name: Build project
        run: |
          echo "=== Start BUILD ==="
          pnpm run build
          if [ ! -d "dist" ]; then
            echo "Build directory not found"
            exit 1
          fi
          echo "=== End BUILD ==="
        continue-on-error: false

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          registry: https://registry.npmjs.org/
        continue-on-error: false
